[package]
name = "status-projets-viewer"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
colored = "3.0.0"
git2 = "0.20.0"
serde = "1.0.218"
serde_derive = "1.0.218"
toml = "0.8.20"

[package.metadata.cargo-machete]
ignored = ["serde"]
